# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/build-tools-ci:6.x
  working_directory: ~/example_drops_8_composer
  environment:
    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/env-vars/
    #
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    # TERMINUS_TOKEN: The Pantheon machine token
    # GITHUB_TOKEN:   The GitHub personal access token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
    #=========================================================================
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"

    # The variables below usually do not need to be modified.

    #======================================================================================================================================
    # Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
    # Once environment variables can be expanded the variables below can be uncommented and the EXPORTs in set-up-globals.sh can be removed
    # See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
    # See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
    # See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
    #======================================================================================================================================

    NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
    ADMIN_USERNAME: admin
    # BUILD_TOOLS_VERSION: ^2.0.0-alpha4
    TERM: dumb

version: 2
jobs:
  configure_env_vars:
    <<: *defaults

    steps:
      - checkout

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      - run:
          name: clone-bash-env
          command: cp $BASH_ENV bash_env.txt

      # https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
      - persist_to_workspace:
          root: .
          paths:
            - bash_env.txt

  static_tests:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-cache-{{ checksum "composer.lock" }}
            - composer-cache-

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      - run:
          name: run static tests
          command: ./.ci/test/static/run

      - save_cache:
          key: composer-cache-{{ checksum "composer.lock" }}
          paths:
            - $HOME/.composer/cache

  build_php:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-cache-{{ checksum "composer.lock" }}
            - composer-cache-
            - vendor-{{ checksum "composer.lock" }}
            - vendor-

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      - run:
          name: run PHP build step
          command: ./.ci/build/php

      - save_cache:
          key: vendor-{{ checksum "composer.lock" }}
          paths:
            - $CIRCLE_WORKING_DIRECTORY/vendor

      - persist_to_workspace:
          root: .
          paths:
            - web
            - vendor
            - drush

  deploy_to_pantheon:
    <<: *defaults
    steps:
      - checkout

      # Attach the workspace
      - attach_workspace:
          at: /tmp

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      # Rsync the build artifact pieces web directory
      - run:
          name: sync build artifact
          command: rsync -rz /tmp/web /tmp/vendor /tmp/drush .

      # Deploy to Pantheon
      - run:
          name: deploy to Pantheon
          command: ./.ci/deploy/pantheon/dev-multidev

  #=======================================================================
  # ASU webspark-upstream updates:
  # Checkout the Webspark upstream, merge the Pantheon upstream
  # to get the newest Pantheon Drupal) and then copy our built
  # code into the codebase, commit and push to the Webspark Release
  # Candidate branch.
  # End this job if we're NOT executing on the default (master) branch.
  # We only merge to webspark-upstream repo's webspark-rc branch
  # for builds of webspark-source repo's master branch.
  # If we merged to webspark-upstream's master, it would be immediately 
  # available, so we merge to webspark-rc branch.
  #=======================================================================
  commit_to_webspark_upstream:
    <<: *defaults
    steps:

      # Halt if we're not building webspark-source master.
      - run: |
          if [ "$CIRCLE_BRANCH" != 'master' ]; then
              circleci-agent step halt
              echo "asu halting"
          fi

      # Attach the workspace with built directories.
      - attach_workspace:
          at: /tmp


      - store_artifacts:
          path: /tmp/vendor
          destination: artifact-vendor
      - store_artifacts:
          path: /tmp/drush
          destination: artifact-drush
      - store_artifacts:
          path: /tmp/web
          destination: artifact-web


      # Add CircleCI RW deploy key so we can push to webspark-upstream repo.
      - add_ssh_keys:
          fingerprints:
            - "c3:77:0e:b2:a2:ac:da:14:07:50:7f:d9:a4:c1:29:e4"
            
      # Need to do this in a separate directory.
      #- run: cd ~

      ##- run:
      ##    name: clone webspark-upstream
      ##    command: git clone https://github.com/Apps-and-Design/webspark-upstream.git ~/webspark-upstream

      ##- run: cd ~/webspark-upstream
      
      ##- run:
      ##    name: checkout webspark-rc staging branch
      ##    command: git checkout -b webspark-rc

      ##- run:
      ##    name: set to the default branch of the drops-8
      ##    command: git checkout -b default

      ##- run: 
      ##    name: add the Drupal 8 Pantheon upstream as a remote
      ##    command: git remote add pantheon-drops-8 git://github.com/pantheon-systems/drops-8.git

      ##- run:
      ##    name: pull in Pantheon Updates and merge, using -Xtheirs (remote takes precedence over local in case of a conflict)
      ##    command: git pull --allow-unrelated-histories --no-edit -X theirs pantheon-drops-8 default

      ##- run: 
      ##    name: check out webspark-rc branch
      ##    command: git checkout webspark-rc

      ##- run:
      ##    name: merge updates but do not commit yet
      ##    command: git merge --no-commit default

      # Rsync Composer built directories into place (if they exist).
      # /tmp/web contains modules/, profiles/, and themes/ and they 
      # need to be synced to root so we sync the contents of /tmp/web/, 
      # not the folder.
      ##- run: |
      ##    for dir in /tmp/vendor /tmp/drush /tmp/web/
      ##    do
      ##        DIR="$dir"
      ##        # If directory is not empty, rsync it.
      ##        if [ "$(ls -A $DIR)" ]; then
      ##            rsync -rz ${dir} ./webspark-upstream
      ##        fi
      ##    done

      # Do rsync in bash script in order to handle logic needed.
      #- run:
      #    name: rsync Composer built files into place
      #    command: bash ../.ci/deploy/asu/webspark-upstream

      ##- run: |
      ##    git config user.email "mlsamuel@asu.edu"
      ##    git config user.name "CircleCI Job"
      ##    git add --all
      ##    git commit -am "CircleCI Upstream Merge - $CIRCLE_BRANCH - $CIRCLE_BUILD_NUM - $CIRCLE_USERNAME"
      ##    git push --set-upstream origin webspark-rc

      #    git push

      #=======================================================================
      # When ready to do release, merge webspark-rc to master via GitHub UI
      # OR do the following on the commandline:
      # git checkout master
      # git merge --no-ff webspark-rc
      # git push origin master
      # TODO Consider automating the above with an approval gateway.
      #=======================================================================

  behat_test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-cache-{{ checksum "composer.lock" }}
            - composer-cache-

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      - run:
          # Uncomment line 26 in .ci/test/behat/initialize to create a backup
          # prior to running Behat tests. This is useful to reset the multidev
          # environment to the previous state after Behat tests have run.
          name: prepare for Behat testing
          command: ./.ci/test/behat/initialize

      - run:
          name: run acceptance tests with Behat
          command: ./.ci/test/behat/run

      - run:
          # Uncomment line 13 in .ci/test/behat/cleanup to restore a backup
          # after running Behat tests. This is useful to reset the multidev
          # environment to the previous state after Behat tests have run.
          name: clean up after Behat
          command: ./.ci/test/behat/cleanup
          when: always

      - save_cache:
          key: composer-cache-{{ checksum "composer.lock" }}
          paths:
            - $HOME/.composer/cache

      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts

  visual_regression_test:
    <<: *defaults
    docker:
      - image: backstopjs/backstopjs:4.1.9
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/workspace

      - run: cp /tmp/workspace/bash_env.txt $BASH_ENV
      - run: echo "export CI_BUILD_URL='${CIRCLE_BUILD_URL}'" >> $BASH_ENV
      - run: echo "export CI_NODE_INDEX='${CIRCLE_NODE_INDEX}'" >> $BASH_ENV
      - run: echo "export CI_REPOSITORY_URL='${CIRCLE_REPOSITORY_URL}'" >> $BASH_ENV
      - run: echo "export ARTIFACTS_DIR_URL='${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/artifacts'" >> $BASH_ENV
      - run: source $BASH_ENV

      - run:
          name: visual regression test
          command: ./.ci/test/visual-regression/run

      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts

  composer_lock_updater:
    <<: *defaults
    steps:
      - checkout

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      - run:
          name: Authenticate with Terminus
          command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

      - run:
          name: run composer lock updater
          command: set -e && terminus project:clu $TERMINUS_SITE

workflows:
  version: 2
  build_deploy_and_test:
    jobs:
      - configure_env_vars
      - static_tests
      - build_php
      - deploy_to_pantheon:
          requires:
            - static_tests
            - build_php
      - commit_to_webspark_upstream:
          requires:
            - deploy_to_pantheon
      - visual_regression_test:
          requires:
            - configure_env_vars
            - deploy_to_pantheon
          filters:
            branches:
              ignore:
                - master
      - behat_test:
          requires:
            - deploy_to_pantheon
            - visual_regression_test

  scheduled_update_check:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
              only:
                - master
    jobs:
      - composer_lock_updater
