#!/bin/bash

#set -eo pipefail
echo "pwd"
pwd

echo "ls -la"
ls -la

echo "ls -la /tmp"
ls -la /tmp

# Rsync Composer built directories into place (if they exist)
for dir in /tmp/vendor /tmp/modules /tmp/profiles /tmp/themes /tmp/drush
do
    DIR="$dir"
    # If directory is not empty, rsync it.
    if [ "$(ls -A $DIR)" ]; then
        rsync -rz ${dir} ./webspark-upstream
    fi
done
# WAS: rsync -rz /tmp/vendor /tmp/modules /tmp/profiles /tmp/themes /tmp/drush ./webspark-upstream
